# Generated by Django 4.1 on 2022-09-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name_plural': 'Families'},
        ),
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
