# Generated by Django 4.1 on 2022-09-13 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_alter_customer_phone_number_alter_vehicle_real_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_rate',
            name='daily_rate',
            field=models.FloatField(),
        ),
    ]
