# Generated by Django 4.1 on 2022-09-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rental_rate_daily_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental_rate',
            name='daily_rate',
            field=models.CharField(max_length=20),
        ),
    ]
